### ISSUE TITLE
TPM_STORE_DIR vs PASSWORD_STORE_DIR

### ISSUE THREAD

**Issue by TAAPArthur** [nmeum/tpm#13]
The README references `PASSWORD_STORE_DIR`, however, the bash/zsh completion scripts reference `TPM_STORE_DIR`.

The completions scripts should be changed to use `PASSWORD_STORE_DIR`.

**Comment by nmeum** [comment]
Good catch! I actually don't use the completion script these days. Will fix that later today. Thanks!
