### ISSUE TITLE
pinentry warning

### ISSUE THREAD

**Issue by orbea** [nmeum/tpm#7]
OS: `Slackware64-current`
`pinentry-1.0.0-x86_64-1`
`tpm-1.3.2-noarch-1_SBo`

Hi, after what I suspect was the recent upgrade to pinentry 1.0.0 in slackware current tpm started spitting out variations of this error. The number of tries is not always the same and sometimes it does not occur, do you have any idea what is causing it? I looked at the script, but I did not really spot anything. Tpm seems to work otherwise, thanks!

`** (pinentry:31018): WARNING **: it took 19 tries to grab the keyboard`

**Comment by Narrat** [comment]
tpm shouldn't be the culprit per se. I noticed this with other tools that use gpg.
Strangely I got rid of those messages after switching the gtk-theme to a more maintained one.
I would suspect that user interaction causes the frequent trials until it got hold of keyboard and mouse, so it is more of a debug message

**Comment by orbea** [comment]
Thanks for the reply, that is my suspicion too that tpm was not the culprit. Its just where I experience it so I hoped you may of had a better idea than I did. :)

I do use a legacy gtk2 theme, but after trying several other gtk2 and gtk3 themes I did not see any change in behavior. Do you mind sharing your gtk theme so I can make sure I didn't try all the wrong ones?

I have meant to try to investigate this further, but I have been rather distracted lately...

**Comment by Narrat** [comment]
I switched from Paper to Arc(-Darker). But I'm almost sure this is just a coincidence :D Although it did happen. But I did not test the other way around.
Maybe it is more likely an update of gtk2/3 helped with that, although didn't investigate that further

**Comment by orbea** [comment]
I haven't seen this warning for a while so I presume something that was updated resolved it. I will close this until it can be reproduced again. Thanks for your time!
